version: '3.8'

networks:
  gv-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  postgres:
    container_name: clinica_lode_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=clinica_lode




